# Generated by Django 4.1.5 on 2023-01-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('sport', 'Sport'), ('music', 'Music'), ('economy', 'Economy'), ('beauty', 'beauty'), ('science', 'science')], default='art', max_length=32, verbose_name='Category'),
        ),
    ]
